### ISSUE TITLE
[Feature] CyberPanel Extension

### ISSUE THREAD

**Issue by CorwinDev** [Paymenter/Extensions#1]
**Is your feature request related to a problem? Please describe.** 
I would like to use the open source CyberPanel, instead of the paid DirectAdmin.

 **Describe the solution you'd like** 
Add CyberPanel to the extensions.
 
 **Describe alternatives you've considered** 
DirectAdmin is available. But you have to pay for DirectAdmin, and it's not open source.
 
 **Additional context** 
For information about CyberPanel's API, visit: https://cyberpanel.docs.apiary.io/

Orginal Issue: https://github.com/Paymenter/Paymenter/issues/66

**Comment by KeizerWilmer** [comment]
CyberPanel just released official API Docs, visit:
https://go.cyberpanel.net/API

**Comment by CorwinDev** [comment]
Added!
